# SITE CONFIGURATION
title: PixelCyber # your site title
# author: GitHub User # You :P
description: > # Meta description of Homepage
  Shu Magic File Viewer
  Thor HTTP Sniffer/Capture
  Anubis API Debug & Inspect
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://pixelcyber.com/" # the base hostname & protocol for your site, e.g. http://example.com

# SEO PLUGIN
# social:
#   name: Your Name
#   links:
#     - https://twitter.com/BenBalter
#     - https://www.facebook.com/ben.balter
#     - https://www.linkedin.com/in/BenBalter
#     - https://plus.google.com/+BenBalter
#     - https://github.com/benbalter
#     - https://keybase.io/benbalter

# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Home', link: '/'}
  - {name: 'About', link: '/about'}
  - {name: 'Contact', link: '/contact'}

tagline: >
  We make awesome apps for you, particularly we created Thor, Shu and Anubis.

hero_img: posts/main_bg.png # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

email: apps@pixelcyber.com # email for form submission

# twitter_username: jan_czizikow # replace with your_twitter_username or comment to remove link from footer
# github_username:  janczizikow # replace with your_github_username or comment to remove link from footer
# instagram_username: shanlongjj # replace with your_instagram_username or comment to remove link from footer

disqus:
  # shortname: PixelCyber # to enable comments replace with your_disqus_shortname

# google_tag_manager: GTM-XXXXXXX # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
# theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
